### ISSUE TITLE
get_accounts does not return a balance

### ISSUE THREAD

**Issue by JaxOfDiamonds** [bvanelli/actualpy#21]
The get_accounts function does not appear to be populating the balances. I have balances in Actual.

Code snippet:

```python
    accounts = get_accounts(actual.session, 'Bank...6877')
    for account in accounts:
        print(account.name)
        print(account)
```

Output:

```
Bank...6877
account_id='ACT-23432-adsfa-40asdf6c-asdf-asdf' balance_current=None balance_available=None mask=None subtype=None offbudget=0 sort_order=None type=None id='234fefas-32423asd-dsfa23-sdf-asdf2' name='Bank...6877' balance_limit=None official_name='COSTLY BLACK' bank='sadfads-asdfa-2dsf-8928adsfasd-2332423' closed=0 tombstone=0
```

**Comment by bvanelli** [comment]
Hello,

I checked the official API, and it was a bit confusing to me because:

- there is a field for storing balance called balance_current that seems to be deprecated, as it does not get filled by the frontend. It seems to only be updated in the sync of external accounts, but it does not get replicated on the server, it's a local value (direct update):

https://github.com/actualbudget/actual/blob/b803731bc52dbf3628b2129c7881cebabd24488e/packages/loot-core/src/server/accounts/sync.ts#L672

- the oficial API actually does not support balance directly in the account object. I actually don't think they support it at all, looking at the docs
- Here is here I think it's actually handled:

https://github.com/actualbudget/actual/blob/b803731bc52dbf3628b2129c7881cebabd24488e/packages/loot-core/src/server/main.ts#L582-L590

I created a patch for now on https://github.com/bvanelli/actualpy/pull/23 that uses an sqlalchemy property. I used the beta token from https://beta-bridge.simplefin.org/info/developers to create an account with lots of entries:

<img width="298" alt="image" src="https://github.com/bvanelli/actualpy/assets/8211602/5734ea0e-a45f-42b3-9b50-007709077624">

The result of the property:

```python
from actual import Actual
from actual.queries import get_accounts


with Actual("http://localhost:5006", password="mypass", file="My Finances") as actual:
    accounts = get_accounts(actual.session)
    for acct in accounts:
        print(f"Balance for {acct.name} is {acct.balance}")
````

```
Balance for SimpleFIN Savings is 115524.49
Balance for SimpleFIN Checking is 26134.41
```

In the general case, I think it would be nice to include the balance on categories, payees and group of transactions. The general query is:

```
def get_balance(transactions: list[Transactions]) -> decimal.Decimal:
    running_balance = decimal.Decimal(0)
    for t in transactions:
        if t.is_parent == 0 and t.tombstone == 0:  # skip the splits, as they already get counted
            amount = t.get_amount()
            running_balance = running_balance + amount
    return running_balance
```

Let me know what you think of the PR, you will be able to install it from git or by cloning and checking out the PR.

**Comment by JaxOfDiamonds** [comment]
The PR worked for me except for an edge case of accounts with zero transactions. I added a comment and a workaround in the PR - though there may be a more elegant solution.

**Comment by bvanelli** [comment]
> The PR worked for me except for an edge case of accounts with zero transactions. I added a comment and a workaround in the PR - though there may be a more elegant solution.

Solved the issue, thanks for the correction!

**Comment by BitNinja01** [comment]
Hey folks! I'm using version 0.8.1 of actualpy and I'm hitting this exact thing.

Code:
```python
accounts = get_accounts(actual.session, 'Discover Debit')
for account in accounts:
	print(account.name)
	print(account)
```

Output:
```
Discover Debit
id='aa5a48ea-09aa-424f-930c-b4762b808781' subtype=None account_id=None offbudget=0 name='Discover Debit' closed=0 balance_current=None tombstone=0 balance_available=None sort_order=16384.0 balance_limit=None type=None mask=None bank_id=None account_sync_source=None official_name=None
```

It's worth noting that this account is _not_ linked to a real bank account (auto-import transactions, etc.), and if I'm understanding this thread correctly that may mean that the balance isn't actually updated in a way accessible to actualpy? Also curious - could these values return "None" if the server is accessed via HTTP instead of HTTPS?

**Comment by bvanelli** [comment]
@BitNinja01 I believe you already discovered the issue, but the fields that are empty were probably meant at some point to be used by them actual guys as the balances caches, but ended up not being.

Since they do not drop the fields I cannot do much about it, but I'll improve documentation of this.
