### ISSUE TITLE
Library can't be used with Home Assistant

### ISSUE THREAD

**Issue by raiyni** [bvanelli/actualpy#86]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of actualpy.

### Reproducible example

I can provide a basic custom component if you really want to devote dev time to this.

### Log output

```shell
"<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
return await handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
return await self._post_impl(request, data)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
return await super()._post_impl(request, data)
2024-10-16 13:48:07.334 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration actual_budget: cannot import name 'TypeAdapter' from 'pydantic' (/usr/local/lib/python3.12/site-packages/pydantic/__init__.cpython-312-x86_64-linux-musl.so)
```

### Issue description

I believe this library can't be used with home assistant as they use version 1.X as stated here https://github.com/home-assistant/core/issues/99218 and from the reported pip version `INSTALLED: 1.10.17`.

It looks like many libraries have migrated away from pydantic? I'm not a python developer by trade so I don't know the cost of doing said migration at this moment but would be willing to help if it meant me being able to use this library without forking it.

### Expected behavior

Not to get an error

### Installed versions

https://github.com/bvanelli/actualpy.git@main

**Comment by bvanelli** [comment]
Hello @raiyni ,

First of all, please also check out https://github.com/jlvcm/actualpy/tree/pydanticv1 and https://github.com/jlvcm/ha-actualbudget, he already did some work downgrading pydantic to v1 and implementing a Home Assistant plugin.

How exactly do you intend to install this library on home automation, by the way?

> It looks like many libraries have migrated away from pydantic

Regarding that, I think that pydantic is very useful as a data model and abstraction layer. Currently the SQL models and the response models depend on pydantic, and I would not change that. It allows me, for example, to convert the names and add documentation to otherwise cryptig fields from the actualbudget data model. If there is a way to offer a better compatibility layer, I would do that instead, but I'm afraid sqlmodel might not support that so well.

**Comment by raiyni** [comment]
Hello

> First of all, please also check out [jlvcm/actualpy@pydanticv1](https://github.com/jlvcm/actualpy/tree/pydanticv1?rgh-link-date=2024-10-17T18%3A24%3A24Z) and [jlvcm/ha-actualbudget](https://github.com/jlvcm/ha-actualbudget), he already did some work downgrading pydantic to v1 and implementing a Home Assistant plugin.


Yes, I did check out their fork and at the time, appeared to have been very behind on their history and hadn't had any activity in either repository for several months. It also appears that they have updated their repositories since opening this issue. I would have to read the diffs more clearly if the commits they have on top are only related to pydantic v1 or if they overwrite some conflicts with their code.

My thought was mainly about using the original (yours) library and not having to maintain a fork of it with a downgraded version of a library and still merge in upstream changes. As that would just greatly decrease time to deploy if there was too much conflicting changes from pydantic v1.


> How exactly do you intend to install this library on home automation, by the way?

Are you asking about usage? Similar to jlvcm's addon, it would be used for pulling budgets, pulling accounts, maybe offering some basic input fields and triggering bank syncs. 

> Regarding that, I think that pydantic is very useful as a data model and abstraction layer. Currently the SQL models and the response models depend on pydantic, and I would not change that. It allows me, for example, to convert the names and add documentation to otherwise cryptig fields from the actualbudget data model. If there is a way to offer a better compatibility layer, I would do that instead, but I'm afraid sqlmodel might not support that so well.

Understandable. It looks like pydantic has added a .v1 compatibility module if that would be more appropriate to maybe integrate?

https://docs.pydantic.dev/latest/migration/#using-pydantic-v1-features-in-a-v1v2-environment

eg usage  https://github.com/YoSmart-Inc/yolink-api/compare/v0.3.1...v0.3.4

**Comment by jlvcm** [comment]
Hi, @raiyni, I've updated  my package with the latest changes from this repo.

I thought about using the compatibility  layer but I don't want to affect @bvanelli work negatively in any way and I'm betting on home assistant eventually upgrading the package, so ended up going this simpler route for now

Feel free to expand on any of my repos, both the HA plugin, and the Actualpy fork, or leave a issue if you need upgrading or have any problem with it and as I'll try to help you as soon as I have some time

Hope my work helps you in any way, thanks 🙏

**Comment by raiyni** [comment]
I don't you closing this @bvanelli  in lieu of @jlvcm's reply, thank you both for your time

**Comment by bvanelli** [comment]
thanks for the replies, I'll try to investigate if pydantic v1 support is something I could implement, if not technically possible I'll close the issue.

**Comment by bvanelli** [comment]
Ok, so I actually tried, and turns out adapting code from version 1 to also work in version two (using the `pydantic.v1` layer) is rather easy, but downgrading pydantic v2 to v1 takes so much effort because there is no backport of most functions, so to keep the same functionality, a lot of things have to be reverted back to the deprecated functions instead. This is especially true for the validators, that have gotten a lot better in v2.

Considering [support for v1 features will be dropped next year](https://github.com/pydantic/pydantic/issues/10033), I don't think it's a good idea to do that. I have tried for around one hour to some patching so that the code runs, and it becomes much much uglier. 😞 

I also find it very unfortunate that the problems with the HA integration are not technical, but rather a lot of people with mixed views of usage of pydantic, some people not merging the change requests or straight up removing pydantic from their requirements.

Let's hope that their migration is at least successful in the next month or two so that a fork is not necessary for so long, since functionality can vary since validators act differently on different library versions.
